# Generated by Django 5.2.16 on 2026-07-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='caratulas/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='clasificacion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='sinopsis',
            field=models.TextField(blank=True, default=''),
        ),
    ]
