# Generated by Django 5.2.16 on 2026-07-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libro_caratula_libro_clasificacion_libro_sinopsis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='caratula',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='clasificacion',
        ),
        migrations.AddField(
            model_name='libro',
            name='categoria',
            field=models.CharField(blank=True, default='Sin Categoría', max_length=100),
        ),
        migrations.AddField(
            model_name='libro',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
    ]
