# Generated by Django 5.2.16 on 2026-07-17 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_remove_libro_caratula_remove_libro_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='es_publico',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='sinopsis',
        ),
    ]
